import { Inter } from "next/font/google";
import "./globals.css";
import Layout from "@/components/applayout/layout";
import { MantineProvider } from "@mantine/core";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <style>{inter.className}</style> {/* Correção para que o estilo seja aplicado dentro do head */}
      </head>
      <body className={inter.className}>
        <MantineProvider>
          <Layout>{children}</Layout>
        </MantineProvider>
      </body>
    </html>
  );
}
  